name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ramesh0112/my-image-name:v1

    - name: Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Push the Docker image
      run: docker push ramesh0112/my-image-name:v1
      
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: ssh
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: deploy
      run:  |
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_INSTANCE_IP }} << EOF
        sudo docker pull ramesh0112/my-image-name:v1
        sudo docker run -itd -p 80:80 --name cont ramesh0112/my-image-name:v1
        EOF
